//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYS_Uyg_4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbSınavÖğrenci2Entities : DbContext
    {
        public DbSınavÖğrenci2Entities()
            : base("name=DbSınavÖğrenci2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDersler> tblDersler { get; set; }
        public virtual DbSet<tblNotlar> tblNotlar { get; set; }
        public virtual DbSet<tblÖğrenci> tblÖğrenci { get; set; }
        public virtual DbSet<tblKulüpler> tblKulüpler { get; set; }
    
        public virtual ObjectResult<Sp_NotListesi_Result> Sp_NotListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_NotListesi_Result>("Sp_NotListesi");
        }
    }
}
