//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYS_Uyg_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKulüpler
    {
        public int KulüpID { get; set; }
        public string KulüpAd { get; set; }
    }
}
