//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYS_Uyg_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblÖğrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblÖğrenci()
        {
            this.tblNotlar = new HashSet<tblNotlar>();
        }
    
        public int ÖğrenciID { get; set; }
        public string ÖğrenciAd { get; set; }
        public string ÖğrenciSoyad { get; set; }
        public string ÖğrenciSehir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotlar> tblNotlar { get; set; }
    }
}
